FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_URLS=http://+:80
USER app

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG CONFIGURATION=Release
WORKDIR /src
COPY ["helloWorld.csproj", "./"]
RUN dotnet restore "helloWorld.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "helloWorld.csproj" -c $CONFIGURATION -o /app/build

FROM build AS publish
ARG CONFIGURATION=Release
RUN dotnet publish helloWorld.csproj -c $CONFIGURATION -o /app/publish /p:UseAppHost=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "helloWorld.dll"]