apiVersion: v1 
kind: Service
metadata:
  name: users-api-svc
  namespace: backend-api
spec:
  type: ClusterIP # ClusterIP NodePort LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: users-api
