apiVersion: v1 
kind: Service
metadata:
  name: groups-api-svc
  namespace: backend-api
spec:
  type: LoadBalancer # ClusterIP NodePort LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: groups-api
