FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
USER app

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG CONFIGURATION=Release
WORKDIR /src
COPY ["ChatP2P.csproj", "./"]
RUN dotnet restore "ChatP2P.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ChatP2P.csproj" -c $CONFIGURATION -o /app/build

FROM build AS publish
ARG CONFIGURATION=Release
RUN dotnet publish ChatP2P.csproj -c $CONFIGURATION -o /app/publish /p:UseAppHost=true

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChatP2P.dll"]